version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cart-postgres
    environment:
      POSTGRES_DB: cart_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - cart_postgres_data:/var/lib/postgresql/data

volumes:
  cart_postgres_data: